name: countDownBot

on: 
  schedule: 
    - cron: 27 18 * * *

jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
      - name: checkout py file 
        uses: actions/checkout@v2
        with: 
          python-version: "3.10.2"
      - name: Install packages 
        run: pip install tweepy
      - name: run the file 
        run: python main.py

        env:
          TWITTER_API_KEY : ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET_KEY : ${{ secrets.TWITTER_API_SECRET_KEY }}
          TWITTER_ACCESS_TOKEN : ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET : ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}








